name = "elentium/voidsentryultimate"
version = "1.0.0"
description = "Schema-driven, validation-free binary serializer for Roblox Luau"
license = "Apache-2.0"
authors = ["IAMNOTULTRA3"]
repository = "https://github.com/Elentium/VoidSentryUltimate"
homepage = "https://elentium.github.io/VoidSentryUltimate/"

includes = [
	"pesde.toml",
	"LICENSE",
	"README.md",
	"src/VoidSentryUltimate.luau",
]

[target]
environment = "roblox"
lib = "src/VoidSentryUltimate.luau"
build_files = ["src/VoidSentryUltimate.luau"]

[indices]
default = "https://github.com/pesde-pkg/index"
